### ISSUE TITLE
Cannot read property '$nuxt' of null

### ISSUE THREAD

**Issue by predragnikolic** [piniajs/example-nuxt-3#10]
Hello :wave:

When I run `yarn isntall` and `yarn dev`,
the following error is displayed:

```
500
Cannot read property '$nuxt' of null
at Module.useNuxtApp (file://./.nuxt/dist/server/server.mjs:243:28)
at Module.useMeta (file://./.nuxt/dist/server/server.mjs:1497:25)
at file://./.nuxt/dist/server/server.mjs:1249:25
at file://./.nuxt/dist/server/server.mjs:186:38
at callWithNuxt (file://./.nuxt/dist/server/server.mjs:230:13)
at applyPlugin (file://./.nuxt/dist/server/server.mjs:186:10)
at Module.applyPlugins (file://./.nuxt/dist/server/server.mjs:191:11)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async createNuxtAppServer (file://./.nuxt/dist/server/server.mjs:34:5)
at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:248:19)
```
Here is my `yarn.lock` if you want to see the installed versions for some packages
[yarn.lock.txt](https://github.com/piniajs/example-nuxt-3/files/7546651/yarn.lock.txt)

**Comment by predragnikolic** [comment]
I deleted the node_modules and run `yarn install` again, and now it works. :)
